In [52]:
import torchvision

from torchvision.transforms import v2

from torchvision import datapoints

import torch
import cv2
import numpy as np

import scipy

import glob
import os

import time

import tqdm

ImportError: cannot import name 'datapoints' from 'torchvision' (c:\Users\admin\miniconda3\envs\aggr_rec\lib\site-packages\torchvision\__init__.py)

In [49]:
def read_video_frames_opencv(path_to_video):
    cap = cv2.VideoCapture(path_to_video)
    frames_list = []
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frames_list.append(frame)


    return torch.tensor(np.array(frames_list).transpose(0, 3, 1, 2))

In [50]:
paths_to_videos_list = glob.glob(r'C:\Users\admin\python_programming\DATA\AVABOS\trash_to_train_on_video\*.mp4')
paths_to_audios_list = glob.glob(r'C:\Users\admin\python_programming\DATA\AVABOS\trash_to_train_on_audio\*.wav')
paths_to_audios_list[0], paths_to_videos_list[0]

('C:\\Users\\admin\\python_programming\\DATA\\AVABOS\\trash_to_train_on_audio\\-kpsb88q2ac(+)_._0.066-10.066_._NOAGGR.wav',
 'C:\\Users\\admin\\python_programming\\DATA\\AVABOS\\trash_to_train_on_video\\-kpsb88q2ac(+)_._0.066-10.066_._NOAGGR.mp4')

In [51]:
paths_to_videos_list = glob.glob(r'C:\Users\admin\python_programming\DATA\AVABOS\trash_to_train_on_video\*.mp4')
paths_to_audios_list = glob.glob(r'C:\Users\admin\python_programming\DATA\AVABOS\trash_to_train_on_audio\*.wav')
times = []
for i in range(100):
    t0 = time.time()
    #a, b, c, = torchvision.io.read_video(paths_to_videos_list[0])
    frames = read_video_frames_opencv(paths_to_videos_list[0])
    audio = scipy.io.wavfile.read(paths_to_audios_list[0])
    times.append(time.time()-t0)

np.mean(times)


0.20736318349838256

In [48]:
transforms = v2.Compose([
    #v2.ToTensor(),
    #v2.RandomResizedCrop(size=(224, 224), antialias=True),
    v2.RandomHorizontalFlip(p=0.5),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

transformed = transforms(frames)

transformed

array([[[[ 81,  73,  95],
         [ 81,  73,  95],
         [ 81,  73,  95],
         ...,
         [147, 153, 189],
         [147, 153, 189],
         [147, 153, 189]],

        [[ 81,  73,  95],
         [ 81,  73,  95],
         [ 81,  73,  95],
         ...,
         [147, 153, 189],
         [147, 153, 189],
         [147, 153, 189]],

        [[ 81,  73,  95],
         [ 81,  73,  95],
         [ 81,  73,  95],
         ...,
         [147, 153, 189],
         [147, 153, 189],
         [147, 153, 189]],

        ...,

        [[134, 143, 149],
         [181, 190, 196],
         [170, 179, 185],
         ...,
         [ 65,  55,  70],
         [ 73,  60,  76],
         [ 74,  61,  77]],

        [[118, 127, 133],
         [136, 145, 151],
         [133, 142, 148],
         ...,
         [ 65,  55,  70],
         [ 68,  55,  71],
         [ 73,  60,  76]],

        [[105, 114, 120],
         [125, 134, 140],
         [120, 129, 135],
         ...,
         [ 63,  53,  68],
        

In [45]:
horizontal_flip = v2.RandomHorizontalFlip(p=0.5)
horizontal_flip(frames)

array([[[[ 81,  73,  95],
         [ 81,  73,  95],
         [ 81,  73,  95],
         ...,
         [147, 153, 189],
         [147, 153, 189],
         [147, 153, 189]],

        [[ 81,  73,  95],
         [ 81,  73,  95],
         [ 81,  73,  95],
         ...,
         [147, 153, 189],
         [147, 153, 189],
         [147, 153, 189]],

        [[ 81,  73,  95],
         [ 81,  73,  95],
         [ 81,  73,  95],
         ...,
         [147, 153, 189],
         [147, 153, 189],
         [147, 153, 189]],

        ...,

        [[134, 143, 149],
         [181, 190, 196],
         [170, 179, 185],
         ...,
         [ 65,  55,  70],
         [ 73,  60,  76],
         [ 74,  61,  77]],

        [[118, 127, 133],
         [136, 145, 151],
         [133, 142, 148],
         ...,
         [ 65,  55,  70],
         [ 68,  55,  71],
         [ 73,  60,  76]],

        [[105, 114, 120],
         [125, 134, 140],
         [120, 129, 135],
         ...,
         [ 63,  53,  68],
        

In [25]:
np.expand_dims(frames, axis=0).shape

(1, 301, 270, 480, 3)

In [40]:
v2.ToTensor()(frames[0])

tensor([[[0.3176, 0.3176, 0.3176,  ..., 0.5765, 0.5765, 0.5765],
         [0.3176, 0.3176, 0.3176,  ..., 0.5765, 0.5765, 0.5765],
         [0.3176, 0.3176, 0.3176,  ..., 0.5765, 0.5765, 0.5765],
         ...,
         [0.5255, 0.7098, 0.6667,  ..., 0.2549, 0.2863, 0.2902],
         [0.4627, 0.5333, 0.5216,  ..., 0.2549, 0.2667, 0.2863],
         [0.4118, 0.4902, 0.4706,  ..., 0.2471, 0.2627, 0.2784]],

        [[0.2863, 0.2863, 0.2863,  ..., 0.6000, 0.6000, 0.6000],
         [0.2863, 0.2863, 0.2863,  ..., 0.6000, 0.6000, 0.6000],
         [0.2863, 0.2863, 0.2863,  ..., 0.6000, 0.6000, 0.6000],
         ...,
         [0.5608, 0.7451, 0.7020,  ..., 0.2157, 0.2353, 0.2392],
         [0.4980, 0.5686, 0.5569,  ..., 0.2157, 0.2157, 0.2353],
         [0.4471, 0.5255, 0.5059,  ..., 0.2078, 0.2118, 0.2275]],

        [[0.3725, 0.3725, 0.3725,  ..., 0.7412, 0.7412, 0.7412],
         [0.3725, 0.3725, 0.3725,  ..., 0.7412, 0.7412, 0.7412],
         [0.3725, 0.3725, 0.3725,  ..., 0.7412, 0.7412, 0.

In [18]:
frames.shape

(301, 270, 480, 3)

In [6]:
c

{'video_fps': 30.0, 'audio_fps': 44100}